# """Add chat_message_id to videos table

# Revision ID: 15f8b737935d
# Revises: 48efb414e07b
# Create Date: 2024-10-20 20:02:31.498850

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '15f8b737935d'
# down_revision: Union[str, None] = '48efb414e07b'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('videos', 'input_text',
#                existing_type=sa.VARCHAR(),
#                type_=sa.Text(),
#                existing_nullable=False)
#     op.create_foreign_key(None, 'videos', 'chat_messages', ['chat_message_id'], ['id'], ondelete='CASCADE')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'videos', type_='foreignkey')
#     op.alter_column('videos', 'input_text',
#                existing_type=sa.Text(),
#                type_=sa.VARCHAR(),
#                existing_nullable=False)
#     # ### end Alembic commands ###

"""Add chat_message_id to videos table

Revision ID: 15f8b737935d
Revises: 48efb414e07b
Create Date: 2024-10-20 20:02:31.498850

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '15f8b737935d'
down_revision = '48efb414e07b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Since chat_message_id column already exists, we skip adding the column
    # Add foreign key for chat_message_id column
    op.create_foreign_key(
        "fk_chat_message_video",  # Explicitly name the foreign key
        'videos',  # Source table
        'chat_messages',  # Destination table
        ['chat_message_id'],  # Source column
        ['id'],  # Destination column
        ondelete='CASCADE'  # Ensure cascading delete behavior
    )

    # Alter input_text column type if needed
    op.alter_column('videos', 'input_text',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Text(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_chat_message_video", 'videos', type_='foreignkey')

    op.alter_column('videos', 'input_text',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    # ### end Alembic commands ###
