# """Add video table

# Revision ID: 8da55ca65fc8
# Revises: 03d559cd17ca
# Create Date: 2024-10-15 22:27:54.434307

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '8da55ca65fc8'
# down_revision: Union[str, None] = '03d559cd17ca'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('video',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('user_id', sa.Integer(), nullable=False),
#     sa.Column('input_text', sa.Text(), nullable=False),
#     sa.Column('video_length', sa.Integer(), nullable=False),
#     sa.Column('file_path', sa.String(length=200), nullable=False),
#     sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('video')
#     # ### end Alembic commands ###

"""Add video table with chat_message_id column

Revision ID: 8da55ca65fc8
Revises: 03d559cd17ca
Create Date: 2024-10-15 22:27:54.434307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da55ca65fc8'
down_revision: Union[str, None] = '03d559cd17ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('input_text', sa.Text(), nullable=False),
        sa.Column('video_length', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=200), nullable=False),
        sa.Column('chat_message_id', sa.Integer(), nullable=True),  # Add chat_message_id column
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    # ### end Alembic commands ###
